displayName=Hide Others Barrows
author=Coopermor
description=A plugin to hide Barrows brothers that aren't yours.
tags=
version=1.0.0
plugins=com.coopermor.hideothersbarrows.HideOthersBarrowsPlugin
build=standard